version: 2

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    meta:
      owner: "Maayan"
    config:
      tags: ["pii"]
      elementary:
        timestamp_column: "signup_date"
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@data-ops"]
              to: ref('stg_signups')
              field: customer_id

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.
        tests:
          - unique:
              config:
                owner: ["@data-ops"]
          - elementary.column_anomalies:
              config:
                owner: ["@data-ops"]
              column_anomalies:
                - missing_count

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments
    meta:
      owner: "Or"
    config:
      tags: ["finance", "sales"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.dimension_anomalies:
          dimensions:
            - customer_id
          config:
            owner: ["@data-ops"]
            tags: ["stability"]
    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@data-ops"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                tags: ["customer_success"]
                severity: warn
                owner: ["@data-ops"]
              values:
                ["placed", "shipped", "completed", "return_pending", "returned"]
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set:
                ["placed", "shipped", "completed", "return_pending", "returned"]
              quote_values: true
              config:
                severity: warn
                owner: ["@data-ops"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                severity: warn
                owner: ["@data-ops"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: returned_orders
    description: This table contains all of the returned orders
    meta:
      owner: "Or"
    config:
      tags: ["finance"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.schema_changes:
          config:
            owner: ["@finance-team"]
    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@customer-team"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                severity: warn
                owner: ["@customer-team"]
              values: ["return_pending", "returned"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                owner: ["@finance-team"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: lost_orders
    description: This table contains all of the lost orders
    meta:
      owner: "Or"
    config:
      tags: ["finance"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.schema_changes_from_baseline
    columns:
      - name: order_id
        description: This is a unique identifier for an order
        data_type: integer

      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - relationships:
              config:
                severity: warn
                owner: ["@customer-team"]
              to: ref('customers')
              field: customer_id

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              config:
                severity: warn
                owner: ["@finance-team"]
              values: ["shipped", "return_pending"]

      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - elementary.column_anomalies:
              config:
                severity: warn
                owner: ["@finance-team"]
              column_anomalies:
                - zero_count
                - zero_percent

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: order_items
    description: "Junction table between orders and products, containing the individual line items per order."
    meta:
      owner: "Maayan"
    config:
      tags: ["sales"]
    columns:
      - name: order_id
        description: "Unique identifier for an order"
      - name: sku
        description: "Unique stock-keeping unit for the item"
      - name: quantity
        description: "Quantity of the sku purchased in the order"
      - name: sale_price
        description: "Sale price of a single unit (AUD)"

  - name: historical_orders
    description: "Orders loaded from the historical batch datasets (prior to the current day). Amount fields are stored in cents."
    meta:
      owner: "Or"
    config:
      tags: ["finance", "sales"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        description: "Unique identifier for an order"
      - name: customer_id
        description: "Foreign key to the customers table"
      - name: order_date
        description: "Date (UTC) the order was placed"
      - name: status
        description: '{{ doc("orders_status") }}'
      - name: amount
        description: "Total order amount (in cents)"
      - name: credit_card_amount
        description: "Portion of the order paid with credit card (in cents)"
      - name: coupon_amount
        description: "Portion of the order paid with coupon (in cents)"
      - name: bank_transfer_amount
        description: "Portion of the order paid with bank transfer (in cents)"
      - name: gift_card_amount
        description: "Portion of the order paid with gift card (in cents)"

  - name: real_time_orders
    description: "Orders ingested from the real-time pipeline for the current day. Monetary fields have already been converted to dollars via the cents_to_dollars macro."
    meta:
      owner: "Or"
    config:
      tags: ["finance", "sales", "real_time"]
      elementary:
        timestamp_column: "order_date"
    columns:
      - name: order_id
        description: "Unique identifier for an order"
      - name: customer_id
        description: "Foreign key to the customers table"
      - name: order_date
        description: "Date (UTC) the order was placed"
      - name: status
        description: '{{ doc("orders_status") }}'
      - name: amount
        description: "Total order amount (AUD) – already converted to dollars"
      - name: credit_card_amount
        description: "Portion of the order paid with credit card (AUD)"
      - name: coupon_amount
        description: "Portion of the order paid with coupon (AUD)"
      - name: bank_transfer_amount
        description: "Portion of the order paid with bank transfer (AUD)"
      - name: gift_card_amount
        description: "Portion of the order paid with gift card (AUD)"
