version: 2

sources:
  - name: ads
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: stg_google_ads
      - name: stg_facebook_ads
      - name: stg_instagram_ads

  - name: sessions
    database: "{{ target.database }}"
    schema: "{{ target.schema }}"
    tables:
      - name: stg_website_sessions
      - name: stg_app_sessions
