version: 2

models:
  - name: ads_spend
    description: "This table contains the daily ad spend, by source, medium and campaign"
    meta:
      owner: "Noa"
    config:
      tags: ["marketing", "finance", "finance-data-product"]
      elementary:
        timestamp_column: "date_day"
    columns:
      - name: date_day
        data_type: date
        description: "Day (UTC) of the ad spend"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

      - name: utm_medium
        data_type: varchar
        description: "The advertising or marketing medium. The medium can be social media, banners, CPC, third-party blogs, etc."

      - name: utm_campain
        data_type: varchar
        description: "The name of the advertising campaign"

      - name: spend
        data_type: number
        description: "The USD amount of money spent"

  - name: attribution_touches
    description: "This is a table that contains all the touch points, by session, with the utm_source, utm_medium and utm_campaign"
    meta:
      owner: "Noa"
    config:
      tags: ["marketing", "pii", "finance-data-product"]
      elementary:
        timestamp_column: "converted_at"
    columns:
      - name: customer_id
        data_type: number
        description: "A unique identifier for a customer"

      - name: session_id
        data_type: varchar
        description: "A unique identifier for a session"

      - name: started_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session started"

      - name: ended_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session ended"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

      - name: utm_medium
        data_type: varchar
        description: "The advertising or marketing medium. The medium can be social media, banners, CPC, third-party blogs, etc."

      - name: utm_campain
        data_type: varchar
        description: "The name of the advertising campaign"

      - name: converted_at
        data_type: timestamp_ntz
        description: "The time of the conversion"

      - name: revenue
        data_type: number
        description: "Revenue amount (USD) of the conversion"

      - name: total_sessions
        data_type: number
        description: "Total number of sessions made by the customer"

      - name: session_index
        data_type: number
        description: "Index of the session"

      - name: first_touch_points
        data_type: number
        description: ""

      - name: last_touch_points
        data_type: number
        description: ""

      - name: forty_twenty_forty_points
        data_type: number
        description: ""

      - name: linear_points
        data_type: number
        description: ""

      - name: first_touch_revenue
        data_type: number
        description: "Revenue amount (USD) of the first touch point"

      - name: last_touch_revenue
        data_type: number
        description: "Revenue amount (USD) of the last touch point"

      - name: forty_twenty_forty_revenue
        data_type: number
        description: ""

      - name: linear_revenue
        data_type: number
        description: ""

  - name: cpa_and_roas
    description: "This table contains the cost per acquisition and return on ad spend, by source, and per month"
    meta:
      owner: "Noa"
    config:
      tags: ["marketing", "finance", "finance-data-product"]
      elementary:
        timestamp_column: "date_month"
    columns:
      - name: date_month
        data_type: timestamp_ntz
        description: "Month (UTC)"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

      - name: attribution_points
        data_type: number
        description: "Total number of attribution points"

      - name: attribution_revenue
        data_type: number
        description: "Total revenue amount (USD)"

      - name: total_spend
        data_type: number
        description: "Total spend amount (USD)"

      - name: cost_per_acquisition
        data_type: number
        description: "Cost (USD) per acquisition, calculated as total_spend / attribution_points"

      - name: return_on_advertising_spend
        data_type: number
        description: "The ROI of the ad spend, calculated as attribution_revenue / total_spend"

  - name: marketing_ads
    description: "This table contains information on the ad spend, by source, medium and campaign"
    meta:
      owner: "Noa"
    config:
      tags: ["marketing", "finance"]
      elementary:
        timestamp_column: "date"
    columns:
      - name: ad_id
        data_type: varchar
        description: "Unique identifier for an ad"

      - name: date
        data_type: date
        description: "date (UTC) when the ad was displayed"

      - name: utm_medium
        data_type: varchar
        description: "The advertising or marketing medium. The medium can be social media, banners, CPC, third-party blogs, etc."

      - name: utm_campain
        data_type: varchar
        description: "The name of the advertising campaign"

      - name: cost
        data_type: number
        description: "Cost (USD) accumulated of the ad presentations so far"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

  - name: agg_sessions
    description: "This table contains aggregated information on the sessions"
    meta:
      owner: "Noa"
    config:
        tags: ["marketing"]
        elementary:
            timestamp_column: "started_at"
    columns:
      - name: session_id
        data_type: varchar
        description: "Unique identifier for a session"

      - name: customer_id
        data_type: number
        description: "Unique identifier for a customer"

      - name: started_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session started"

      - name: ended_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session ended"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

      - name: ad_id
        data_type: varchar
        description: "Unique identifier for an ad"

      - name: platform
        data_type: varchar
        description: "Platform where the session was made. For example, website, iOS app, Android app, etc."

  - name: customer_conversions
    description: "This table contains information on the conversions of all the customers"
    meta:
      owner: "Noa"
    config:
        tags: ["marketing", "finance", "pii"]
        elementary:
            timestamp_column: "converted_at"
    columns:
      - name: customer_id
        data_type: number
        description: "Unique identifier for a customer"

      - name: converted_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the conversion happened"

      - name: revenue
        data_type: number
        description: "Total revenue amount (USD) of the conversion"

  - name: sessions
    description: "This table contains information on the sessions of all the customers and the utm_source, utm_medium and utm_campaign of the session"
    meta:
      owner: "Noa"
    config:
        tags: ["marketing", "pii"]
        elementary:
            timestamp_column: "started_at"
    columns:
      - name: session_id
        data_type: varchar
        description: "Unique identifier for a session"

      - name: customer_id
        data_type: number
        description: "Unique identifier for a customer"

      - name: started_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session started"

      - name: ended_at
        data_type: timestamp_ntz
        description: "Time (UTC) when the session ended"

      - name: utm_source
        data_type: varchar
        description: "Source where the ad was displayed. For example, Google, Facebook, Twitter, Newsletter, etc."

      - name: utm_medium
        data_type: varchar
        description: "The advertising or marketing medium. The medium can be social media, banners, CPC, third-party blogs, etc."

      - name: utm_campain
        data_type: varchar
        description: "The name of the advertising campaign"