# This workflow runs the Cursor Agent on a user-provided prompt.
# To use this workflow, you need to set a repository secret named CURSOR_API_KEY.
# You can get your API key from your Cursor settings.
name: Run Cursor Agent

on:
  push:
    branches:
      - cursor-agent-action
  workflow_dispatch:
    inputs:
      prompt:
        description: 'The prompt for the Cursor Agent to execute.'
        required: true
        default: 'Describe the project in three sentences.'

jobs:
  run-cursor-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cursor Agent
        run: curl https://cursor.com/install -fsS | bash

      - name: Run Cursor Agent
        run: cursor-agent "${{ github.event.inputs.prompt || 'Describe the project in three sentences.' }}"
        env:
          CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
